#!/usr/bin/env python

from KoPFA.TopAnalyzer.HistDataset import *

import sys, os
from ROOT import *

gROOT.SetStyle("Plain")
gStyle.SetOptTitle(0)
gStyle.SetOptStat(0)

def initSample7TeV(mode):
    ds = HistDataset(mode)
    dir = "/users/jhgoh/work/CMS/TopAnalysis/hist/hist/"+mode

    ds.addData("Run2011", dir+"/vallot_Run2011.root", kBlack, 5000)

    ds.addSignal("TTbar", "t#bar{t}#rightarrowll", dir+"/vallot_TTbarTuneZ2.root", kRed+1, 157.5)

    ds.addBackground("TTbarOthers", "t#bar{t} others", dir+"/vallot_TTbarOthers.root", kRed-7, 157.5)
    ds.addBackground("WJets", "W#rightarrowl#nu", dir+"/vallot_WJetsToLNu.root", kGreen-3, 31314)
    ds.addBackground("WW", "VV", dir+"/vallot_WW.root", kGray+4, 4.51)
    ds.addBackground("WZ", "VV", dir+"/vallot_WZ.root", kGray+4, 0.61)
    ds.addBackground("ZZ", "VV", dir+"/vallot_ZZ.root", kGray+4, 7.4)
    #ds.addBackground("SingleTopBartW", "SingleTop", dir+"/vallot_SingleTopBartW.root", kMagenta, 7.87/2)
    ds.addBackground("SingleToptW", "SingleTop", dir+"/vallot_SingleToptW.root", kMagenta, 7.87)
    ds.addBackground("ZtauDecay", "Z/#gamma#rightarrow#tau#tau", dir+"/vallot_ZtauDecay.root", kAzure+8, 3048)
    ds.addBackground("ZtauDecay10To50", "Z/#gamma#rightarrow#tau#tau", dir+"/vallot_ZtauDecay10To50.root", kAzure+8, 11908.83)
    ds.addBackground("ZJets", "Z/#gamma#rightarrowll", dir+"/vallot_ZJets.root", kAzure-2, 3048)
    ds.addBackground("ZJets10To50", "Z/#gamma#rightarrowll", dir+"/vallot_ZJets10To50.root", kAzure-2, 11908.83)

    return ds

if __name__ == "__main__":
    dMuMu = initSample7TeV("MuMu")
    dElEl = initSample7TeV("ElEl")
    dMuEl = initSample7TeV("MuEl")

    dMuMu.listSamples()
    dElEl.listSamples()
    dMuEl.listSamples()

    dMuMu.printCutSteps()
    dElEl.printCutSteps()
    dMuEl.printCutSteps()

    histSetup = {
        #"Step[0-1]/hrelIso[12]":{},
        "Step[1-4]/hZMass":{"y":(0.5, 1e6),"logy":True},
        #"Step[4-6]/hNJet":{"y":(0.5,1e6),"logy":True},
        #"Step[4-6]/hMET":{"y":(0.5, 1e6),"logy":True},
        #"Step[4-6]/hjet1pt":{"logy":True},
        "Step4/hvsumM":{"y":(0, 10000),"logy":False,"x":(0,200,300,350,400,450,500,600,800,1000)},
        "Step[56]/hvsumM":{"y":(0, 5000),"logy":False,"x":(0, 345, 400, 450, 500, 550, 600, 680, 800, 1800)},
        "Step[56]/hmaosM":{"y":(0, 5000),"logy":False,"x":(0, 345, 400, 450, 500, 550, 600, 680, 800, 1800)},
    }

    dMuMu.draw(histSetup)
    dElEl.draw(histSetup)
    dMuEl.draw(histSetup)

