import FWCore.ParameterSet.Config as cms

genBJets = cms.EDProducer("GenBJetSelector",
    genParticle = cms.InputTag("genParticles"),
    genJet = cms.InputTag("ak5GenJets"),
    matchAlgos = cms.vstring(
        #"BquarkDeltaR", 
        #"BHadronDeltaR",
        #"BquarkOverlap",
        #"BHadronOverlap",
        "BquarkFrac",
        #"BHadronFrac",
    ),
    #maxDeltaR = cms.double(999),
    #maxMatchDeltaR = cms.double(999),
    #minNMatchBquark = cms.int32(0),
    #minNMatchBHadron = cms.int32(0),
    #minFracBquark = cms.double(0),
    #minFracBHadron = cms.double(0),
    maxDeltaR = cms.double(0.5),
    maxMatchDeltaR = cms.double(999),
    minNMatchBquark = cms.int32(10),
    minNMatchBHadron = cms.int32(3),
    minFracBquark = cms.double(0.05),
    minFracBHadron = cms.double(0.3),
    doHist = cms.untracked.bool(True),
)
