#cmsBatch.py -o Out/11 1 dimuonanalyzer_pileup_1_cfg.py -r /castor/cern.ch/user/t/tjkim/ntuple/RD/Aug9th/pileup1/vallot.root -q 1nh 
#cmsBatch.py -o Out/12 1 dimuonanalyzer_pileup_2_cfg.py -r /castor/cern.ch/user/t/tjkim/ntuple/RD/Aug9th/pileup2/vallot.root -q 1nh 
#cmsBatch.py -o Out/13 1 dimuonanalyzer_pileup_3_cfg.py -r /castor/cern.ch/user/t/tjkim/ntuple/RD/Aug9th/pileup3/vallot.root -q 1nh 
cmsBatch.py -o Out/14 1 dimuonanalyzer_pileup_4_cfg.py -r /castor/cern.ch/user/t/tjkim/ntuple/RD/Aug9th/pileup4/vallot.root -q 1nh 
#cmsBatch.py -o Out/2 1 dimuonanalyzer_nopileup_cfg.py -r /castor/cern.ch/user/t/tjkim/ntuple/RD/Aug9th/nopileup/vallot.root -q 1nh 
#cmsBatch.py -o Out/21 1 dimuonanalyzer_nopileup_1_cfg.py -r /castor/cern.ch/user/t/tjkim/ntuple/RD/Aug9th/nopileup1/vallot.root -q 1nh 
#cmsBatch.py -o Out/22 1 dimuonanalyzer_nopileup_2_cfg.py -r /castor/cern.ch/user/t/tjkim/ntuple/RD/Aug9th/nopileup2/vallot.root -q 1nh 
#cmsBatch.py -o Out/23 1 dimuonanalyzer_nopileup_3_cfg.py -r /castor/cern.ch/user/t/tjkim/ntuple/RD/Aug9th/nopileup3/vallot.root -q 1nh 
#cmsBatch.py -o Out/24 1 dimuonanalyzer_nopileup_4_cfg.py -r /castor/cern.ch/user/t/tjkim/ntuple/RD/Aug9th/nopileup4/vallot.root -q 1nh 
