
import FWCore.ParameterSet.Config as cms

readFiles = cms.untracked.vstring()
source = cms.Source("PoolSource",
		     noEventSort = cms.untracked.bool(True),
		     duplicateCheckMode = cms.untracked.string("noDuplicateCheck"),
		     fileNames = readFiles
                    )
readFiles.extend([
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_10_1_2B9.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_11_1_Ipy.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_12_1_w2Q.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_13_1_Sxn.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_14_1_1qe.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_15_1_DBq.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_16_1_j5O.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_17_1_9cG.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_18_1_oXi.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_19_1_7TH.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_1_1_zgZ.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_20_1_hPb.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_21_1_R4k.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_22_1_fy2.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_23_1_DfH.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_24_1_XoR.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_25_1_QCb.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_26_1_IiB.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_27_1_Xju.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_28_1_jVj.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_29_1_pKn.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_2_1_810.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_30_1_Zim.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_31_1_ZtO.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_32_1_3Yb.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_33_1_W94.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_34_1_aTC.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_35_1_pBZ.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_36_1_ms2.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_37_1_cVb.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_38_1_CFH.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_39_1_an6.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_3_1_dZ8.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_40_1_htF.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_41_1_sne.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_42_1_gt0.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_43_1_A45.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_44_1_bcF.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_45_1_1Uy.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_46_1_9NS.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_47_1_KKk.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_48_1_aLT.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_49_1_V8t.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_4_1_rNx.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_50_1_vxx.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_5_1_epm.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_6_1_tk8.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_7_1_wco.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_8_1_Yt0.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Nov22_TightMU/Run2010B-Nov4ReReco_v1/patTuple_skim_9_1_Z69.root',
]
        )
