
import FWCore.ParameterSet.Config as cms

readFiles = cms.untracked.vstring()
source = cms.Source("PoolSource",
		     noEventSort = cms.untracked.bool(True),
		     duplicateCheckMode = cms.untracked.string("noDuplicateCheck"),
		     fileNames = readFiles
                    )
readFiles.extend([
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_10_0_wlQ.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_11_1_KHO.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_12_0_2D2.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_13_0_OWK.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_14_1_0mJ.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_15_0_mMo.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_16_0_ML3.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_17_0_iDi.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_18_1_QNg.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_19_0_uXC.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_1_1_gg0.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_20_1_Lgv.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_21_1_7WB.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_22_1_c7t.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_23_1_ZPM.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_24_1_K0Y.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_25_0_bZy.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_26_0_VWR.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_27_1_JFG.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_28_1_5IC.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_29_0_QWw.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_2_0_Lrg.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_30_1_dmH.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_31_1_tTN.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_32_1_EO5.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_33_1_TXi.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_34_1_F8r.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_35_1_No3.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_36_0_DNn.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_37_1_4sR.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_38_1_b2f.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_39_0_8BM.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_3_0_XFu.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_40_1_wy3.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_41_1_ZRN.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_42_1_CeC.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_43_0_GUf.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_44_0_C17.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_45_1_7bZ.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_46_1_Tcg.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_47_0_EIs.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_48_0_nqz.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_49_1_Y9Y.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_4_0_KKG.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_50_1_FvQ.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_51_0_hzm.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_52_0_m2a.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_53_1_811.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_54_1_RQ0.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_55_0_Ejb.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_56_1_yZ9.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_57_0_sMz.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_58_0_Anf.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_59_1_LjQ.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_5_0_iZs.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_60_0_DAo.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_61_1_aLp.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_62_1_iyb.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_63_0_Yma.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_64_1_sYn.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_65_1_00X.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_6_1_yZq.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_7_1_PsW.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_8_0_iz4.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_9_1_KDa.root',
]
        )
