
import FWCore.ParameterSet.Config as cms

readFiles = cms.untracked.vstring()
source = cms.Source("PoolSource",
		     noEventSort = cms.untracked.bool(True),
		     duplicateCheckMode = cms.untracked.string("noDuplicateCheck"),
		     fileNames = readFiles
                    )
readFiles.extend([
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_10_0_pSE.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_11_0_YNe.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_12_0_UJc.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_13_0_lOZ.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_14_0_Tqx.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_15_0_daL.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_16_0_2Fk.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_17_0_qBA.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_18_1_RxB.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_19_0_avi.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_1_1_ICq.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_20_1_lhw.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_21_0_Ymz.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_22_1_tGX.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_23_0_fe0.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_24_0_rFq.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_25_0_5mm.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_26_0_9oX.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_27_0_Lge.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_28_0_IlA.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_29_0_Mgw.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_2_0_YiI.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_30_0_lFI.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_31_0_qzW.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_32_0_cXx.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_33_0_bRL.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_34_0_lh4.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_35_0_5Vx.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_36_0_SqX.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_37_0_lju.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_38_0_Bih.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_39_0_PlM.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_3_0_o6G.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_40_0_OLf.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_41_1_xBN.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_42_0_U4z.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_43_0_zZD.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_44_0_kKl.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_45_1_l3H.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_46_1_oms.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_47_0_dPW.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_48_0_uqE.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_49_0_L1J.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_4_0_bf1.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_50_0_qqe.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_51_0_bIi.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_52_0_UXO.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_53_0_x7G.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_54_0_s5g.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_55_0_Mqu.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_56_0_QAi.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_57_0_Gs0.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_58_0_qU4.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_59_0_fqL.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_5_0_6x1.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_60_0_p3z.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_61_0_Cas.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_62_0_8Pn.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_63_0_qWU.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_64_1_NDz.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_65_1_Mbm.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_6_1_3sN.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_7_0_8O5.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_8_0_k6K.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_9_0_hoo.root',
]
        )
