
import FWCore.ParameterSet.Config as cms

readFiles = cms.untracked.vstring()
source = cms.Source("PoolSource",
		     noEventSort = cms.untracked.bool(True),
		     duplicateCheckMode = cms.untracked.string("noDuplicateCheck"),
		     fileNames = readFiles
                    )
readFiles.extend([
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_10_0_X66.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_11_0_YQR.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_12_0_ZKP.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_13_0_awT.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_14_0_keY.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_15_0_NJO.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_16_0_b8r.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_17_0_GoN.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_18_1_udy.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_19_0_lgd.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_1_2_wI7.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_20_1_R72.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_21_0_gxc.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_22_1_LVR.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_23_0_huE.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_24_0_klj.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_25_0_WRv.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_26_0_ntn.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_27_0_XrX.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_28_0_q64.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_29_0_VQl.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_2_0_stX.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_30_0_xTS.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_31_0_DA6.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_32_0_7MQ.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_33_0_Fqw.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_34_0_fwQ.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_35_0_dSl.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_36_0_O5H.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_37_0_kWX.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_38_0_1Ue.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_39_0_b2d.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_3_0_RHj.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_40_0_AMq.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_41_2_7bc.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_42_0_HMo.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_43_0_g1q.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_44_0_Lc2.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_45_2_wpn.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_46_1_oQM.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_47_0_8fm.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_48_0_by3.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_49_0_16z.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_4_0_t2L.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_50_0_RKO.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_51_0_98W.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_52_0_nNw.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_53_0_eKK.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_54_0_PWh.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_55_0_iFw.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_56_0_QWi.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_57_0_ciU.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_58_0_SEp.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_59_0_50W.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_5_0_NLy.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_60_0_Suq.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_61_0_ihE.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_62_0_eY0.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_63_0_61R.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_64_1_ftg.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_65_2_YX5.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_6_2_jYQ.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_7_0_Wb4.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_8_0_VWg.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13/Commissioning10-SD_Mu-Jun14thSkim_v1/patTuple_muon_9_0_oRz.root',
]
        )
