
import FWCore.ParameterSet.Config as cms

readFiles = cms.untracked.vstring()
source = cms.Source("PoolSource",
		     noEventSort = cms.untracked.bool(True),
		     duplicateCheckMode = cms.untracked.string("noDuplicateCheck"),
		     fileNames = readFiles
                    )
readFiles.extend([
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_10_1_xYF.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_11_1_YwG.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_12_1_s4l.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_13_1_ui7.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_14_1_KTB.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_15_1_ZZd.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_16_1_T7s.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_17_1_DYk.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_18_1_56c.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_19_1_n9z.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_1_1_yrr.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_20_0_h2g.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_21_1_NGz.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_22_1_OHD.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_23_1_bn0.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_24_1_hgs.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_25_1_p1Y.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_26_1_KrE.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_27_0_bdB.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_28_1_Dpt.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_29_0_0Gg.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_2_1_CrT.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_30_1_Yvl.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_31_0_2PI.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_32_1_mx7.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_33_0_htq.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_34_1_D1f.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_35_1_peS.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_36_1_S7F.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_37_0_eSS.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_38_1_7fh.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_39_1_YG9.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_3_1_hlN.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_40_1_6Su.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_41_1_fUq.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_42_0_Fq3.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_43_1_qu9.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_44_1_C3v.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_45_1_5ss.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_46_0_vUy.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_4_1_xmn.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_5_1_gz8.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_6_1_dLs.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_7_1_oNt.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_8_1_fk0.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUONSKIM/Aug9th/Run2010A-Jul16thReReco-v1/patTuple_muon_9_1_fwz.root',
]
        )
