import FWCore.ParameterSet.Config as cms

MuMuJPsiMuMu = cms.EDFilter("CMGmmJPsimmFilter",
  muonLabel1 =  cms.InputTag('Muons'),
  muonLabel2 =  cms.InputTag('Muons'),
  muonLabel3 =  cms.InputTag('Muons'),
  muonLabel4 =  cms.InputTag('Muons'),
  min = cms.double(12),
  max = cms.double(99999),
  relIso1 = cms.untracked.double(0.15),
  relIso2 = cms.untracked.double(0.15),
  rhoIsoLabel =  cms.untracked.InputTag('kt6PFJets','rho'),
  vertexLabel = cms.untracked.InputTag('offlinePrimaryVertices'),
  #beamSpotTag = cms.InputTag("offlineBeamSpot"), 
)

MuMuJPsiElEl = cms.EDFilter("CMGmmJPsieeFilter",
  muonLabel1 =  cms.InputTag('Muons'),
  muonLabel2 =  cms.InputTag('Muons'),
  muonLabel3 =  cms.InputTag('Electrons'),
  muonLabel4 =  cms.InputTag('Electrons'),
  min = cms.double(12),
  max = cms.double(99999),
  relIso1 = cms.untracked.double(0.15),
  relIso2 = cms.untracked.double(0.15),
  rhoIsoLabel =  cms.untracked.InputTag('kt6PFJets','rho'),
  vertexLabel = cms.untracked.InputTag('offlinePrimaryVertices'),
  #beamSpotTag = cms.InputTag("offlineBeamSpot"),
) 

MuElJPsiMuMu = cms.EDFilter("CMGmeJPsimmFilter",
  muonLabel1 =  cms.InputTag('Muons'),
  muonLabel2 =  cms.InputTag('Electrons'),
  muonLabel3 =  cms.InputTag('Muons'),
  muonLabel4 =  cms.InputTag('Muons'),
  min = cms.double(12),
  max = cms.double(99999),
  relIso1 = cms.untracked.double(0.15),
  relIso2 = cms.untracked.double(0.15),
  rhoIsoLabel =  cms.untracked.InputTag('kt6PFJets','rho'),
  vertexLabel = cms.untracked.InputTag('offlinePrimaryVertices'),
  #beamSpotTag = cms.InputTag("offlineBeamSpot"),
)

MuElJPsiElEl = cms.EDFilter("CMGmeJPsieeFilter",
  muonLabel1 =  cms.InputTag('Muons'),
  muonLabel2 =  cms.InputTag('Electrons'),
  muonLabel3 =  cms.InputTag('Electrons'),
  muonLabel4 =  cms.InputTag('Electrons'),
  min = cms.double(12),
  max = cms.double(99999),
  relIso1 = cms.untracked.double(0.15),
  relIso2 = cms.untracked.double(0.15),
  rhoIsoLabel =  cms.untracked.InputTag('kt6PFJets','rho'),
  vertexLabel = cms.untracked.InputTag('offlinePrimaryVertices'),
  #beamSpotTag = cms.InputTag("offlineBeamSpot"),
)

ElElJPsiMuMu = cms.EDFilter("CMGeeJPsimmFilter",
  muonLabel1 =  cms.InputTag('Electrons'),
  muonLabel2 =  cms.InputTag('Electrons'),
  muonLabel3 =  cms.InputTag('Muons'),
  muonLabel4 =  cms.InputTag('Muons'),
  min = cms.double(12),
  max = cms.double(99999),
  relIso1 = cms.untracked.double(0.15),
  relIso2 = cms.untracked.double(0.15),
  rhoIsoLabel =  cms.untracked.InputTag('kt6PFJets','rho'),
  vertexLabel = cms.untracked.InputTag('offlinePrimaryVertices'),
  #beamSpotTag = cms.InputTag("offlineBeamSpot"),
)

ElElJPsiElEl = cms.EDFilter("CMGeeJPsieeFilter",
  muonLabel1 =  cms.InputTag('Electrons'),
  muonLabel2 =  cms.InputTag('Electrons'),
  muonLabel3 =  cms.InputTag('Electrons'),
  muonLabel4 =  cms.InputTag('Electrons'),
  min = cms.double(12),
  max = cms.double(99999),
  relIso1 = cms.untracked.double(0.15),
  relIso2 = cms.untracked.double(0.15),
  rhoIsoLabel =  cms.untracked.InputTag('kt6PFJets','rho'),
  vertexLabel = cms.untracked.InputTag('offlinePrimaryVertices'),
  #beamSpotTag = cms.InputTag("offlineBeamSpot"),
)

