rfrm -r /castor/cern.ch/user/t/tjkim/ntuple/MC/Spring10/InclusiveMu15
rfrm -r /castor/cern.ch/user/t/tjkim/ntuple/MC/Spring10/TTbar
rfrm -r /castor/cern.ch/user/t/tjkim/ntuple/MC/Spring10/Zmumu
rfrm -r /castor/cern.ch/user/t/tjkim/ntuple/MC/Spring10/Ztautau
rfrm -r /castor/cern.ch/user/t/tjkim/ntuple/MC/Spring10/ZJets
rfrm -r /castor/cern.ch/user/t/tjkim/ntuple/MC/Spring10/WJets
rfrm -r /castor/cern.ch/user/t/tjkim/ntuple/MC/Spring10/VVJets
rfrm -r /castor/cern.ch/user/t/tjkim/ntuple/MC/Spring10/SingleTop
rfrm -r /castor/cern.ch/user/t/tjkim/ntuple/MC/Spring10/DYmumu
