rm -rf InclusiveMu15
rm -rf ppMuX 
rm -rf Zmumu 
rm -rf Ztautau 
rm -rf TTbar2l 
rm -rf TTbar 
rm -rf Wmunu 
rm -rf Wtaunu  
rm -rf DYmumu_M10to20
rm -rf QCD_Pt15
rm -rf QCD_Pt30 
rm -rf ZJets
rm -rf WJets
