
import FWCore.ParameterSet.Config as cms

readFiles = cms.untracked.vstring()
source = cms.Source("PoolSource",
		     noEventSort = cms.untracked.bool(True),
		     duplicateCheckMode = cms.untracked.string("noDuplicateCheck"),
		     fileNames = readFiles
                    )
readFiles.extend([
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_10_1_Rla.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_11_1_lVb.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_12_1_Nhu.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_13_1_CAC.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_14_1_FAG.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_15_1_2pU.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_16_1_aoh.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_17_1_Ptn.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_18_1_0HU.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_19_1_LZE.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_1_1_pHV.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_20_1_gbI.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_21_1_159.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_22_1_GIM.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_23_1_MLJ.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_24_1_Oz8.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_25_1_nno.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_26_1_7f8.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_27_1_JWa.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_28_1_Dk2.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_29_1_JvS.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_2_1_BtW.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_30_1_TKX.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_31_1_OJy.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_32_1_2Mj.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_33_1_3yw.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_34_1_TKx.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_35_1_Gst.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_36_1_RlP.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_37_1_sPj.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_38_1_Dwt.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_39_1_Lvu.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_3_1_krw.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_40_1_0ab.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_41_1_I7Y.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_42_1_wEJ.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_43_1_52m.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_44_1_O7x.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_45_1_mjt.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_46_1_iz4.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_47_1_8nW.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_48_1_4zu.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_49_1_OaC.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_4_1_Y4A.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_50_1_zTy.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_51_1_hXV.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_52_1_LXH.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_53_1_osX.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_54_1_PPH.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_5_1_H5y.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_6_1_0UO.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_7_1_IEz.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_8_1_fFr.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/Wmu_v2/patTuple_skim_9_1_px1.root',
]
        )
