
import FWCore.ParameterSet.Config as cms

readFiles = cms.untracked.vstring()
source = cms.Source("PoolSource",
		     noEventSort = cms.untracked.bool(True),
		     duplicateCheckMode = cms.untracked.string("noDuplicateCheck"),
		     fileNames = readFiles
                    )
readFiles.extend([
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_10_0_KId.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_11_0_QBs.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_12_0_eoz.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_13_0_5ho.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_14_0_lpU.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_15_0_iWY.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_16_0_Uuk.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_17_0_B6P.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_18_0_oh5.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_19_0_lYG.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_1_1_kiv.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_20_0_loS.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_21_0_xKe.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_22_0_EvD.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_23_0_vbv.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_24_0_oHE.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_25_0_2wj.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_26_0_uNb.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_27_0_oO1.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_28_0_r2r.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_29_0_kOb.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_2_1_SH9.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_30_0_9db.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_31_0_UpK.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_32_0_opF.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_33_0_id8.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_34_0_EwY.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_35_0_FZD.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_36_0_Pcd.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_37_0_AKV.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_38_0_9Co.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_39_0_nvN.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_3_0_AxD.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_40_0_9VZ.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_41_0_prT.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_42_0_neT.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_43_0_Rc7.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_44_0_9Wr.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_45_0_iVJ.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_46_0_IjO.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_47_0_2jK.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_48_0_fYQ.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_49_0_1HS.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_4_0_rx8.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_50_0_Jz0.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_51_0_KpK.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_52_0_2RW.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_53_0_lYx.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_54_0_WFL.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_55_0_8Ez.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_56_0_ckj.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_5_0_Ry3.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_6_0_d98.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_7_0_OmO.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_8_0_Qec.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/MC/Fall10_TightMU/QCD_Pt_15to30/patTuple_skim_9_0_o6C.root',
]
        )
