
import FWCore.ParameterSet.Config as cms

readFiles = cms.untracked.vstring()
source = cms.Source("PoolSource",
		     noEventSort = cms.untracked.bool(True),
		     duplicateCheckMode = cms.untracked.string("noDuplicateCheck"),
		     fileNames = readFiles
                    )
readFiles.extend([
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_10_1_fwu.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_11_1_cOI.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_12_1_Cdl.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_13_1_YFB.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_14_1_5MS.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_15_1_g32.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_16_1_gpw.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_17_1_lOl.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_18_1_wpm.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_19_1_azK.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_1_1_MaN.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_20_0_WAR.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_21_1_2e6.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_22_1_MGX.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_23_1_EdS.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_24_1_alB.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_25_1_FFe.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_26_1_oMf.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_27_1_cgK.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_28_1_5V9.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_29_1_PAA.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_2_1_Kag.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_30_1_Zhv.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_31_0_nfl.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_32_1_h2W.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_33_0_qMx.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_34_1_366.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_35_1_wlE.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_36_1_Lrv.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_37_0_ket.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_38_1_IYD.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_39_1_Sa9.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_3_1_u3V.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_40_1_b2u.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_41_1_QaS.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_42_0_IbU.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_43_1_pPp.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_44_1_z7N.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_45_1_Xow.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_46_0_zl4.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_4_2_TIC.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_5_1_vtl.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_6_1_G9N.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_7_1_Id5.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_8_1_FTq.root',
	'rfio:///castor/cern.ch/user/t/tjkim/MUSKIM/Aug13_nopileup/Run2010A-Jul16thReReco-v1/patTuple_muon_9_1_WVz.root',
]
        )
